language: minimal

branches:
  only:
    - actionfun

script:
  - git checkout https://github.com/nebularg/PackagerTest.git PackagerTest
  - ./release.sh -t PackagerTest -ldp 1

notifications:
  email: false
