name: WoW Packager
description: Builds and publishes World of Warcraft AddOns
branding:
  icon: package
  color: yellow
inputs:
  path:
    description: 'Top-level directory of the addon'
    required: false
    default: ${{ github.workspace }}
  args:
    description: 'Command-line arguments'
    required: false
    default: ''
runs:
  using: composite
  steps:
    # install pandoc if appropriate. this keeps parity with the docker action (but you should probably apt install it)
    - run: pandoc -v &>/dev/null || { [ -n "$WOWI_API_TOKEN" ] && curl -sfL "$(curl -sf https://api.github.com/repos/jgm/pandoc/releases/latest | jq -r '.assets[] | select(.content_type == "application/x-gzip") | .browser_download_url' 2>/dev/null)" | sudo tar -xzf - --strip=1 -C /usr/local &>/dev/null; } || true
      shell: bash
    # curl is scary
    - run: cd ${{ inputs.path }} && $GITHUB_ACTION_PATH/release.sh ${{ inputs.args }}
      shell: bash
