name: WoW Packager
description: Builds and publishes World of Warcraft AddOns
branding:
  icon: package
  color: yellow
inputs:
  args:
    description: 'Command-line arguments'
    required: false
    default: ''
runs:
  using: composite
  steps:
    # install pandoc if appropriate
    - run: [ -n "$WOWI_API_TOKEN" ] && sudo apt-get install -yq pandoc &>/dev/null
      shell: bash
    # curl is scary
    - run: $GITHUB_ACTION_PATH/release.sh ${{ inputs.args }}
      shell: bash
