name: WoW Packager
description: Build and publish World of Warcraft AddOns
branding:
  icon: package
  color: yellow
inputs:
  args:
    description: 'Command-line arguments. See https://github.com/BigWigsMods/packager#usage'
    required: false
  pandoc:
    description: 'Install pandoc before packaging if uploading to WoWInterface.'
    required: false
    default: true
runs:
  using: composite
  steps:
    # install pandoc if appropriate
    - run: sudo apt-get install -yq pandoc &>/dev/null && echo -e "##[group]pandoc version\n[command]pandoc --version\n$(pandoc --version)\n##[endgroup]"
      shell: bash
    - run: echo "wowi:${WOWI_API_TOKEN:+set}; pandoc:${{ inputs.pandoc }};"
      shell: bash
    - run: $GITHUB_ACTION_PATH/release.sh ${{ inputs.args }}
      shell: bash
