name: WoW Packager
description: Builds and publishes World of Warcraft AddOns
branding:
  icon: package
  color: yellow
inputs:
  path:
    description: 'Top-level directory of the addon'
    required: false
    default: ${{ github.workspace }}
  args:
    description: 'Command-Line Arguments'
    required: false
    default: ''
runs:
  using: composite
  steps:
    # force pandoc on the container
    - run: pandoc -v &>/dev/null || { [ -n "$WOWI_API_TOKEN" ] && curl -sL $(curl -s https://api.github.com/repos/jgm/pandoc/releases/latest | jq -r '.assets[] | select(.content_type == "application/x-gzip") | .browser_download_url') | sudo tar xzf - --strip-components=1 -C /usr/local &>/dev/null; } || true
      shell: bash
    - run: cd ${{ inputs.path }} && $GITHUB_ACTION_PATH/release.sh ${{ inputs.args }}
      shell: bash
