name: WoW Packager
description: Builds and publishes World of Warcraft AddOns
branding:
  icon: package
  color: yellow
inputs:
  args:
    description: 'Command-Line Arguments'
    required: false
    default: ''
  topdir:
    description: 'Top-level directory of checkout'
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
    - run: cd ${${{ inputs.topdir }}//\\/\/}
      shell: bash
    - run: $GITHUB_ACTION_PATH/release.sh ${{ inputs.args }}
      shell: bash
