name: WoW Packager
description: Build and publish World of Warcraft AddOns
branding:
  icon: package
  color: yellow
inputs:
  args:
    description: 'Command-line arguments. See https://github.com/BigWigsMods/packager#usage'
    required: false
  pandoc:
    description: 'Install pandoc before packaging if uploading to WoWInterface.'
    required: false
    default: true
runs:
  using: composite
  steps:
    # install pandoc if appropriate
    - run: '[[ -n "$WOWI_API_TOKEN" && "${{ inputs.pandoc }}" == "true" ]] && sudo apt-get install -yq pandoc &>/dev/null && echo -e "##[group]Install pandoc\n[command]pandoc --version\n$(pandoc --version)\n##[endgroup]" || true'
      shell: bash
    - run: $GITHUB_ACTION_PATH/release.sh ${{ inputs.args }}
      shell: bash
