name: WoW Packager
description: Builds and publishes World of Warcraft AddOns
branding:
  icon: package
  color: yellow
inputs:
  path:
    description: 'Top-level directory of the addon'
    required: false
    default: ${{ github.workspace }}
  args:
    description: 'Command-Line Arguments'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - run: cd ${{ inputs.path }}
      shell: bash
    - run: $GITHUB_ACTION_PATH/release.sh ${{ inputs.args }}
      shell: bash
